import Header from '@/components/layouts/Header/Header'
import ReactQueryJotaiProvider from './ReactQueryJotaiProvider'
import './globals.css'
import Footer from '@/components/layouts/Footer/Footer'
import { notoSansKR } from '@/styles/theme/typography'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <ReactQueryJotaiProvider>
      <html lang="ko">
        <body className={`${notoSansKR.className}`}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ReactQueryJotaiProvider>
  )
}
