import StyledComponentsRegistry from '@/lib/registry'
import ReactQueryJotaiProvider from './ReactQueryJotaiProvider'
import { notoSansKR } from '@/styles/theme/font'
import GlobalHooks from '@/components/GlobalHooks'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <ReactQueryJotaiProvider>
      <html lang="ko" className={`${notoSansKR.className}`}>
        <body>
          <GlobalHooks />
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </html>
    </ReactQueryJotaiProvider>
  )
}
